stages:
  - triggers

trigger_frontEnd:
  stage: triggers
  trigger:
    include: FrontEnd/.gitlab-ci.yml
  rules:
    - changes:
        - FrontEnd/*

trigger_backEnd:
  stage: triggers
  trigger:
    include: BackEnd/.gitlab-ci.yml
  rules:
    - changes:
        - BackEnd/*

